sudo: required

services:
  - docker

env:
  global:
    - IMAGENAME=go-micro-test
    - GOOS=linux
    - CGO_ENABLED=0

language: go
go:
  - 1.7.x

before_install:
  - go get -v -u ./...

install:
  # build our Go application
  - go build -v --ldflags '-extldflags "-static"' -o main

before_script:
  # build Docker image with compiled code, lauch side containers for testings
  - docker version
  - time docker build -t $IMAGENAME --build-arg GIT_COMMIT=$TRAVIS_COMMIT --build-arg GIT_BRANCH=$TRAVIS_BRANCH  -f Dockerfile_alpine .
  - docker images
  - docker run -d -p 8080:8080 $IMAGENAME
  - docker ps

script:
  - curl http://localhost:8080/stats

#after_success:
#  # deploy artifacts, etc
#  - docker tag go-docker-test1 skandyla/go-docker-test1:latest
#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push skandyla/go-docker-test1:latest

#deploy:
#    provider: bintray
#    file: "Path to a descriptor file, containing information for the Bintray upload"
#    user: "Bintray user"
#    key: "Bintray API key"
#    passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
#    dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration"
