language: go
go:
  - 1.7.x
sudo: required
services:
  - docker

env:
  global:
    - CGO_ENABLED=0
#    - IMAGENAME=go-micro-test
#    - DOCKERUSER=skandyla
#    - GOOS=linux


before_install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - make

after_success:
  #- make deploy
  - make docker-tag
  - make docker-push

#deploy:
#    provider: bintray
#    file: "Path to a descriptor file, containing information for the Bintray upload"
#    user: "Bintray user"
#    key: "Bintray API key"
#    passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
#    dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration"
